version: '3'

services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    volumes:
      - wp_volume:/var/www/html
    ports:
      - "443:443"
    env_file:
      - .env
    restart: always
    networks:
      - nat
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: always
    networks:
      - nat
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_volume:/var/www/html
    env_file:
      - .env
    expose:
      - 9000
    restart: always
    networks:
      - nat

networks:
  nat:

volumes:
  wp_volume: