version: '3'

services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    volumes:
      - wp_files:/var/www/html
      - wp_db:/var/lib/mysql
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - nat
    depends_on:
      - wordpress
    restart: on-failure

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - nat
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_files:/var/www/html
    env_file:
      - .env
    expose:
      - 9000
    networks:
      - nat
    restart: on-failure

  static_website:
    build: ./requirements/bonus/staticwebsite
    image: static_website
    container_name: static_website
    ports:
      - "1337:80"
    networks:
      - nat
    restart: on-failure

networks:
  nat:

volumes:
  wp_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device : ${PWD}/srcs/wp_db
  wp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device : ${PWD}/srcs/wp_files