version: '3'

services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    volumes:
      - wp_files:/var/www/html
      - wp_db:/var/lib/mysql
    ports:
      - "443:443"
    env_file:
      - .env
    restart: always
    networks:
      - nat
    depends_on:
      - wordpress

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      - wp_db:/var/lib/mysql
    restart: always
    networks:
      - nat

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_files:/var/www/html
    env_file:
      - .env
    expose:
      - 9000
    restart: always
    networks:
      - nat

networks:
  nat:

volumes:
  wp_db:
    # driver: local
    # driver_opts:
    #   type: local
    #   o: bind
    #   device: /my/volume/location
  wp_files:
