version: '3'

services:
  nginx:
    build: ./requirements/nginx/
    image: nginx:1337
    container_name: nginx
    volumes:
      - wp_files:/var/www/html
      - wp_db:/var/lib/mysql
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - internal_network
    depends_on:
      - wordpress
    restart: on-failure

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:1337
    container_name: mariadb
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - internal_network
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:1337
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_files:/var/www/html
    env_file:
      - .env
    expose:
      - 9000
    networks:
      - internal_network
    restart: on-failure

  static_website:
    build: ./requirements/bonus/staticwebsite
    image: static_website:1337
    container_name: static_website
    ports:
      - "1337:80"
    networks:
      - internal_network
    restart: on-failure

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:1337
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - internal_network
    restart: on-failure

networks:
  internal_network:

volumes:
  wp_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device : /home/ooumlil/data/wp_db
  wp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device : /home/ooumlil/data/wp_files
