#!/bin/bash

service mysql start\
&& mysql -u root -e \
"CREATE DATABASE IF NOT EXISTS $DATABASE_NAME;\
CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';\
GRANT ALL PRIVILEGES ON $DATABASE_NAME.* TO '$MYSQL_USER'@'%';\
FLUSH PRIVILEGES;"

service mysql stop

exec "$@"
